server:
  port: 8080
  tomcat:
    accesslog:
      enabled: true       #是否打印accesslog日志。为true时为打印（默认是false）
      buffered: false      #用于确定是否将缓冲日志记录的标志。如果设置为false，则将在每个请求之后写入访问日志。默认值：true
      directory: ./    # 日志文件存放的路径
      prefix: access_log    # 日志名称前缀
      suffix: .log    # 日志名称后缀
      file-date-format: -yyyy-MM-dd   # 日志文件名中的日期格式。以天为单位
      pattern: '%{X-Real-IP}i - %{Host}i %t "%r" %{Content-Length}i %s %b %D "%{Referer}i" "%{User-Agent}i" %a "%I" "-"'   # 见下
      rotate: true    # 是否启用日志轮转。默认为true（这个参数决定是否需要切换切换日志文件，如果被设置为false，则日志文件不会切换，即所有文件打到同一个日志文件中，并且file-date-format参数也会被忽略）
spring:
  datasource:
    url: jdbc:mysql:#localhost:3306/yellowducktrainsystem?characterEncoding=UTF-8
    username: username
    password: password
    driver-class-name: com.mysql.cj.jdbc.Driver
  thymeleaf:
    prefix: classpath:/templates/
    suffix: .html
    mode: LEGACYHTML5
    encoding: utf-8
    cache: false
    servlet:
      content-type: text/html
  resources:
    chain:
      strategy:
        content:
          paths: /**
          enabled: true
druid:
  initial-size: 5
  min-idle: 1
  max-active: 20
  query-timeout: 6000
  remove-abandoned: false
  #必须要remove-abandoned为false才能生效，这样连接出问题的时候，每隔3000秒请求
  async-init: true
  time-between-connect-error-millis: 3000
  #先关着
  log-abandoned: false
  transaction-query-timeout: 6000
  remove-abandoned-timeout: 1800
  filters: wall,stat
  connection-properties: druid.stat.mergeSql=true;druid.stat.slowSqlMillis=10000
  stat-view-servlet:
    login-username: bda
    login-password: bda
    url-pattern: /druid/*
    reset-enable: false
  web-stat-filter:
    url-pattern: /*
    exclusions: "*.js,*.gif,*.jpg,*.bmp,*.png,*.css,*.ico,/druid/*"
    #超时重试次数
  connection-error-retry-attempts: 3
  #必须为false（失败后会不断请求数据库，请求在TIME-WAIT，在数据库服务重启后，所有等待请求会访问数据库），
  #为true上面参数才会生效（：true表示pool向数据库上面的重试请求连接此时失败后标记整个pool为block并close，
  #就算后端数据库恢复正常也不进行重连，客户端对pool的请求都拒绝掉。false表示不会标记 pool为block，新的请求都会尝试去数据库请求connection。
  #默认为false。因此，如果想让数据库和网络故障恢复之后，pool能继续请求正常资源必须把此项配置设为false）
  break-after-acquire-failure: false
  #检查连接正常的sql
  validation-query: select 1 from dual
  #配置多久检测一次空闲连接（可以选择是否尽早关闭连接，看压力在server还是数据库端）
  time-between-eviction-runs-millis: 60000
  #数据库连接最小生存时间
  min-evictable-idle-time-millis: 300000
logging:
  config: classpath:log4j2.yml

mybatis:
  type-aliases-package: cn.yellowgg.ducksystem.entity
  mapperLocations: classpath:mapper/*.xml
  configuration:
    map-underscore-to-camel-case: true

